version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:3000"
  mysql:
    container_name: running_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'eekhoorntje'
      MYSQL_PASS: 'mysqlpass'
volumes:
  my-datavolume:/var/lib/mysql